name: medical_app_belinda_full
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_database: ^10.2.5
  url_launcher: ^6.1.14
  google_ml_kit: ^0.16.2
  table_calendar: ^3.0.9
  flutter_local_notifications: ^15.1.1
  flutter_timezone: ^1.0.7
  timezone: ^0.9.2
  device_info_plus: ^9.0.3
  go_router: ^10.1.2
#  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true




